/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ManualFrame.java
 *
 * Created on 2009-11-5, 14:35:58
 */
package userinterfaces;

/**
 *
 * @author CaoZhichao
 */
public class ManualFrame extends javax.swing.JFrame {

    /** Creates new form ManualFrame */
    public ManualFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sensor Simulator Manual");

        jTextArea1.setColumns(20);
        jTextArea1.setEditable(false);
        jTextArea1.setRows(5);
        jTextArea1.setText("Sensor Simulator\n\nRun:\n1. select source file to transmit\n2. configure settings\n3. click advance button to configure advance settings\n4. click save button to save settings\n5. click confirm button to continue\n6. click run button in the new window to start\n\nSettings:\n1. Sensor: the type of sensor to simulate\n2. Source file: the source file to transmit\n3. Transmit based on: transmit the source file based\non the time stamp in source file or the frequency\nspecified by user\n4. Time Stamp Position: the position of the timestamp\ncolumn in the source file. The first column, the \nlast column or no time stamp in source file\n5. Frequency: the user specified frequency,\nfrequency mode only\n\nAdvance settings\n1. Output byte order: the data byte order in the\noutput packet\n2.  Data unit format: the format of the data field\nin the output packet\n3. Frequency Margin: the accuracy between real\nfrequency and user specified frequency\n4. Channel Number: how many channels (data fields) \nin the source file\n5.  Include time stamp: whether to send the time \nstamp at transmission to receiver");
        jTextArea1.setSelectionEnd(1077);
        jTextArea1.setSelectionStart(1077);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jButton1)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ManualFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
